### ISSUE TITLE
ubuntu Python3.6 安装0.3.2错误

### ISSUE THREAD

**Issue by wezhyn** [HaveTwoBrush/cn2an#11]
完整异常日志:
``` python
  Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0xvk4tfr/cn2an/setup.py", line 4, in <module>
        from cn2an import version
      File "/tmp/pip-build-0xvk4tfr/cn2an/cn2an/__init__.py", line 9, in <module>
        cn2an = cn2an.Cn2An().cn2an
      File "/tmp/pip-build-0xvk4tfr/cn2an/cn2an/cn2an.py", line 9, in __init__
        self.conf = utils.get_default_conf()
      File "/tmp/pip-build-0xvk4tfr/cn2an/cn2an/utils.py", line 8, in get_default_conf
        config_data = yaml.load(f_config, Loader=yaml.FullLoader)
      File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 112, in load
        loader = Loader(stream)
      File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 24, in __init__
        Reader.__init__(self, stream)
      File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
        self.determine_encoding()
      File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
        self.update_raw()
      File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw
        data = self.stream.read(size)
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 15: ordinal not in range(128)
    
    ----------------------------------------
```
换成0.3.1正常

**Comment by HaveTwoBrush** [comment]
这是我在 `Ubuntu 16.04` 上使用 `python 3.6.6` 测试结果：
![Screenshot from 2019-05-25 15-28-26](https://user-images.githubusercontent.com/7982046/58366302-d3b49480-7f02-11e9-9dfb-d66e86aec298.png)

你能给出更详细的信息吗？

1. 系统版本
2. python 的具体版本
3. 问题发生的状态，比如是在 pip install 还是 python setup.py install ?
4. 问题发生时上下文的截图。

祝周末愉快～

**Comment by wezhyn** [comment]
### 系统环境
* docker run -it --rm ubuntu
* apt-get update && apt-get install  -y python3 python3-pip 
* pip3 install pyyaml
后来遇到字符串的统一问题，发现是docker默认的系统语言不是utf-8而导致的，现在已经解决
export LANG=C.UTF-8
