### ISSUE TITLE
utils.py 指定 encoding="UTF-8"

### ISSUE THREAD

**Issue by OpenWaygate** [HaveTwoBrush/cn2an#13]
直接安装报错, 下载安装也报错
```
cd cn2an && python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from cn2an import version
  \cn2an\cn2an\__init__.py", line 9, in <module>
    cn2an = cn2an.Cn2An().cn2an
  \cn2an\cn2an\cn2an.py", line 9, in __init__
    self.conf = utils.get_default_conf()
  File "\cn2an\cn2an\utils.py", line 8, in get_default_conf
    config_data = yaml.load(f_config, Loader=yaml.FullLoader)
  File "C:\Python\envs\37\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Python\envs\37\lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "C:\Python\envs\37\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Python\envs\37\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Python\envs\37\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb6 in position 18: illegal multibyte sequence
```

改一下`utils.py`, 指定`encoding`解决了
```
import os
import yaml


def get_default_conf():
    with open(f"{os.path.dirname(__file__)}/config.yaml", "r", encoding="UTF-8") as f_config:
        config_data = yaml.load(f_config, Loader=yaml.FullLoader)
    return config_data
```

**Comment by HaveTwoBrush** [comment]
这个问题被反馈过很多次，下个版本我会在所有需要的地方加上 utf-8 编码。
