### ISSUE TITLE
官方文档有三个例子不能用

### ISSUE THREAD

**Issue by thouger** [HaveTwoBrush/cn2an#16]
尝试了
cn2an.cn2an("一二三") 
cn2an.cn2an("1百23", "smart")
cn2an.an2cn("1百23", "smart")
这三个都不能用

这是出错情况:
>>> cn2an.cn2an("1百23", "smart")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\softdown\python3.6.6\lib\site-packages\cn2an\cn2an.py", line 17, in cn2an
    data_type = self.check_input_data_is_valid(inputs, mode)
  File "D:\softdown\python3.6.6\lib\site-packages\cn2an\cn2an.py", line 42, in check_input_data_is_valid
    raise ValueError(f"输入的数据不在转化范围内：{data}！")
ValueError: 输入的数据不在转化范围内：1！
>>> cn2an.cn2an("一二三")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\softdown\python3.6.6\lib\site-packages\cn2an\cn2an.py", line 17, in cn2an
    data_type = self.check_input_data_is_valid(inputs, mode)
  File "D:\softdown\python3.6.6\lib\site-packages\cn2an\cn2an.py", line 65, in check_input_data_is_valid
    raise ValueError(f"不符合格式的数据：{integer_data}")
ValueError: 不符合格式的数据：一二三
>>> cn2an.an2cn("1百23", "smart")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\softdown\python3.6.6\lib\site-packages\cn2an\an2cn.py", line 11, in an2cn
    raise ValueError("mode 仅支持 low up rmb smart 四种！")
ValueError: mode 仅支持 low up rmb smart 四种！

cn2an版本是0.3.6
python版本是3.6.6
系统是windows10

**Comment by thouger** [comment]
我观察了ValueError: mode 仅支持 low up rmb smart 四种！这种情况,是因为在an2cn.py文件中,An2Cn类里面的an2cn函数只判断"low", "up", "rmb"，而raise异常却是提示四个:"mode 仅支持 low up rmb smart 四种！"
![QQ图片20190820103836](https://user-images.githubusercontent.com/11767062/63313926-a8dab080-c338-11e9-9719-7330770cf3fd.png)
其他还没看

**Comment by HaveTwoBrush** [comment]
这是我文档写的有问题，先前在构建的时候是打算一起写完的，目前还有 smart 模式未完成，我会在下个版本的更新中解决这个问题。

cn2an.cn2an("一二三") 出错的原因是：默认 mode 是 strict，而`一二三`并非严格的十进位数字，需要使用 normal 的 mode，即：
```python
print(cn2an.cn2an("一二三", "normal")
# output: 123
```
