### ISSUE TITLE
导入错误!

### ISSUE THREAD

**Issue by liuhe6** [HaveTwoBrush/cn2an#3]
import cn2an
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liuhe/anaconda3/lib/python3.6/site-packages/cn2an-0.1.2-py3.6.egg/cn2an/__init__.py", line 11, in <module>
    cn2an = cn2an.Cn2An().cn2an
  File "/home/liuhe/anaconda3/lib/python3.6/site-packages/cn2an-0.1.2-py3.6.egg/cn2an/cn2an.py", line 11, in __init__
    self.conf = utils.get_default_conf()
  File "/home/liuhe/anaconda3/lib/python3.6/site-packages/cn2an-0.1.2-py3.6.egg/cn2an/utils.py", line 7, in get_default_conf
    with codecs.open("./cn2an/config.yaml", "r", encoding="utf-8") as f_config:
  File "/home/liuhe/anaconda3/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './cn2an/config.yaml'

**Comment by liuhe6** [comment]
解决了...在utils里把config的路径改成绝对路径就行了，不过搞不明白为啥之前的相对路径会错
